export const TEACHER_DEFAULT_PRESETS = [
  { name: "Lesson Planning",                  sprint: 4, estMinutes: 60,  workCategory: "STANDARD", notes: "activities, slides, materials, UDL" },
  { name: "Collaborative Planning",           sprint: 4, estMinutes: 60,  workCategory: "STANDARD", notes: "unit design, resource creation, alignment" },
  { name: "Unit Building",                    sprint: 4, estMinutes: 90,  workCategory: "STANDARD", notes: "task-specific rubrics, concepts, timelines" },
  { name: "Formative Feedback",               sprint: 2, estMinutes: 100, workCategory: "GRADING",  notes: "per class" },
  { name: "Summative Assessment",             sprint: 2, estMinutes: 100, workCategory: "GRADING",  notes: "per class" },
  { name: "Moderation",                       sprint: 2, estMinutes: 60,  workCategory: "GRADING",  notes: "" },
  { name: "Lesson/Tools/Materials Setup",     sprint: 1, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "Materials Prep",                   sprint: 3, estMinutes: 30,  workCategory: "STANDARD", notes: "wood, plywood, acrylic, cardboard, robots, etc." },
  { name: "Check Missing Work",               sprint: 1, estMinutes: 10,  workCategory: "STANDARD", notes: "beginning of class" },
  { name: "Advisory Prep",                    sprint: 3, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "Parent Email",                     sprint: 3, estMinutes: 10,  workCategory: "STANDARD", notes: "" },
  { name: "Unit Newsletter",                  sprint: 3, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "Pre-Unit Reflection",              sprint: 4, estMinutes: 10,  workCategory: "STANDARD", notes: "" },
  { name: "Mid-Unit Reflection",              sprint: 4, estMinutes: 10,  workCategory: "STANDARD", notes: "" },
  { name: "Post-Unit Reflection",             sprint: 4, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "Post Assessments",                 sprint: 3, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "Student Spotlight / Recognition",  sprint: 3, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "Update Timelines / Planning Docs", sprint: 3, estMinutes: 30,  workCategory: "STANDARD", notes: "" },
  { name: "Write Professional Article / Blog",sprint: 4, estMinutes: 120, workCategory: "STANDARD", notes: "" },
  { name: "Create Instructional Video",       sprint: 4, estMinutes: 90,  workCategory: "STANDARD", notes: "" },
  { name: "Practice/Learn Design Software",   sprint: 4, estMinutes: 60,  workCategory: "STANDARD", notes: "" },
  { name: "Reimbursement Submission",         sprint: 3, estMinutes: 15,  workCategory: "STANDARD", notes: "" },
  { name: "SST Tracking",                     sprint: 3, estMinutes: 20,  workCategory: "STANDARD", notes: "" },
  { name: "Monthly Budget Check-In",          sprint: 3, estMinutes: 20,  workCategory: "STANDARD", notes: "" },
];

export const STUDENT_DEFAULT_PRESETS = [
  { name: "Homework",             sprint: 4, estMinutes: 30, workCategory: "STANDARD", notes: "per subject" },
  { name: "Study / Review",       sprint: 4, estMinutes: 45, workCategory: "STANDARD", notes: "" },
  { name: "Formative Assessment", sprint: 2, estMinutes: 60, workCategory: "GRADING",  notes: "per class" },
  { name: "Summative Assessment", sprint: 2, estMinutes: 90, workCategory: "GRADING",  notes: "per class" },
  { name: "IXL",                  sprint: 3, estMinutes: 20, workCategory: "STANDARD", notes: "" },
  { name: "Form / Return",        sprint: 3, estMinutes: 10, workCategory: "STANDARD", notes: "" },
  { name: "Reading",              sprint: 4, estMinutes: 30, workCategory: "STANDARD", notes: "" },
  { name: "Project Work",         sprint: 4, estMinutes: 60, workCategory: "STANDARD", notes: "" },
];
